name: Build Kompendium PDF

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "Kompendium/**"
      - "Tools/**"
      - "PandocDefaultOptionSettings.yaml"
      - "Regeln.md"
      - ".github/workflows/build-kompendium-pdf.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "Kompendium/**"
      - "Tools/**"
  release:
    types: [ published ]

permissions:
  contents: write   # nötig, um Assets an Releases anzuhängen

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Pandoc + LaTeX-Engine (xelatex) installieren
      - name: Install build dependencies (pandoc + TeX)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            pandoc texlive-xetex texlive-fonts-recommended texlive-plain-generic \
            fonts-dejavu fonts-liberation
          pandoc --version

      # Optional: PowerShell-Version anzeigen (pwsh ist auf ubuntu-latest vorinstalliert)
      - name: PowerShell info
        shell: pwsh
        run: '$PSVersionTable'

      # Dein bestehendes Build-Script ausführen
      - name: Build Kompendium
        shell: pwsh
        run: |
          ./Tools/Build-Kompendium.ps1 -ErrorAction Stop
          if (-not (Test-Path "./PowerShell_Kompendium.pdf")) {
            Write-Error "PDF nicht gefunden. Stelle sicher, dass Build-Kompendium.ps1 die Datei 'PowerShell_Kompendium.pdf' erzeugt."
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PowerShell_Kompendium.pdf
          path: PowerShell_Kompendium.pdf
          if-no-files-found: error
          retention-days: 14

      # Bei Release zusätzlich als Asset anhängen
      - name: Attach to release
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: softprops/action-gh-release@v2
        with:
          files: PowerShell_Kompendium.pdf
