name: Build Kompendium PDF


on:
push:
branches: [ main ]
paths: [ "Kapitel_*.md", "tools/Build-Kompendium.ps1", ".github/workflows/build-kompendium-pdf.yml" ]
pull_request:
branches: [ main ]
paths: [ "Kapitel_*.md", "tools/Build-Kompendium.ps1" ]
workflow_dispatch: {}
release:
types: [created]


permissions:
contents: write


jobs:
build:
name: Build PDF
runs-on: ubuntu-latest


steps:
- name: Checkout
uses: actions/checkout@v4


- name: Setup PowerShell
uses: PowerShell/PowerShell@v1
with:
powershell-version: '7.4.x'


- name: Build master markdown (Kompendium.md)
shell: pwsh
run: |
./tools/Build-Kompendium.ps1 -Verbose


- name: Build PDF with Pandoc (LaTeX)
run: |
docker run --rm \
-v "$PWD:/data" \
pandoc/latex:latest \
pandoc Kompendium.md \
-o PowerShell_Kompendium.pdf \
--pdf-engine=xelatex \
--toc --toc-depth=2 \
--metadata title="PowerShell meistern" \
--metadata author="Attila Krick" \
--from=gfm


- name: Upload artifact
uses: actions/upload-artifact@v4
with:
name: PowerShell_Kompendium_PDF
path: PowerShell_Kompendium.pdf
if-no-files-found: error


release:
name: Attach PDF to Release
needs: build
runs-on: ubuntu-latest
if: github.event_name == 'release'
steps:
- name: Checkout
uses: actions/checkout@v4


- name: Download artifact
uses: actions/download-artifact@v4
with:
name: PowerShell_Kompendium_PDF
path: dist


- name: Upload to GitHub Release
uses: softprops/action-gh-release@v2
with:
files: dist/PowerShell_Kompendium.pdf
